In [62]:
import numpy as np 
import pandas as pd

## Data Loading

In [63]:
df = pd.read_csv(r"C:\Users\rampa\DS Python Class\Baking Loan\Data\Row Data\banking_loan_row_data.csv")

## Data Understanding

In [64]:
df.head()

,Customer_ID,Application_Date,Age,Gender,Employment_Type,Annual_Income,City,Credit_Score,Loan_Type,Loan_Tenure_Years,Loan_Amount,Approval_Status,Loan_Status,Payment_Delay_Days
0,CUST100001,2024-04-12,32,Male,Salaried,450814.0,Mumbai,760,Personal Loan,7,1079635,Approved,Active,24
1,CUST100002,2025-03-11,56,Male,Business,1991401.0,Pune,768,Personal Loan,20,1139453,Approved,Overdue,84
2,CUST100003,2026-05-10,41,Male,Salaried,1722785.0,Nagpur,650,Home Loan,5,2492582,Approved,Active,0
3,CUST100004,2024-09-27,39,Male,Salaried,1237476.0,Nashik,731,Auto Loan,5,1201000,Approved,Active,0
4,CUST100005,2024-04-16,23,Male,Salaried,1224284.0,Thane,702,Auto Loan,2,1597533,Approved,Active,16

In [65]:
df.tail()

,Customer_ID,Application_Date,Age,Gender,Employment_Type,Annual_Income,City,Credit_Score,Loan_Type,Loan_Tenure_Years,Loan_Amount,Approval_Status,Loan_Status,Payment_Delay_Days
99995,CUST199996,2024-08-11,53,Male,Salaried,1389082.0,Amravati,728,Personal Loan,7,691082,Approved,Active,0
99996,CUST199997,2025-08-03,31,Female,Salaried,399902.0,Mumbai,690,Home Loan,10,4844811,Rejected,Rejected,0
99997,CUST199998,2024-12-12,48,Female,Salaried,2004045.0,Pune,643,Home Loan,10,5532924,Rejected,Rejected,0
99998,CUST199999,2026-05-12,36,Female,Salaried,972867.0,Nagpur,674,Education Loan,7,251655,Approved,Closed,0
99999,CUST200000,2025-01-08,65,Male,Business,682378.0,Nashik,738,Home Loan,20,2903088,Approved,Default,109

In [66]:
df.columns.tolist()

['Customer_ID',
 'Application_Date',
 'Age',
 'Gender',
 'Employment_Type',
 'Annual_Income',
 'City',
 'Credit_Score',
 'Loan_Type',
 'Loan_Tenure_Years',
 'Loan_Amount',
 'Approval_Status',
 'Loan_Status',
 'Payment_Delay_Days']

In [67]:
df.dtypes

Customer_ID            object
Application_Date       object
Age                     int64
Gender                 object
Employment_Type        object
Annual_Income         float64
City                   object
Credit_Score            int64
Loan_Type              object
Loan_Tenure_Years       int64
Loan_Amount            object
Approval_Status        object
Loan_Status            object
Payment_Delay_Days      int64
dtype: object

## Basic Satastics

In [68]:
df.describe()

,Age,Annual_Income,Credit_Score,Loan_Tenure_Years,Payment_Delay_Days
count,100000.000000,1.000000e+05,100000.00000,100000.000000,100000.000000
mean,43.011230,1.374660e+06,694.48915,10.209140,9.947220
std,12.984126,6.494167e+05,64.63646,6.741559,24.518884
min,21.000000,2.500010e+05,419.00000,1.000000,0.000000
25%,32.000000,8.120880e+05,651.00000,5.000000,0.000000
50%,43.000000,1.376598e+06,695.00000,10.000000,0.000000
75%,54.000000,1.936224e+06,739.00000,15.000000,11.000000
max,65.000000,2.499985e+06,850.00000,25.000000,180.000000

In [69]:
df.describe(include="object")

,Customer_ID,Application_Date,Gender,Employment_Type,City,Loan_Type,Loan_Amount,Approval_Status,Loan_Status
count,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,100000,1004,2,12,36,5,98286,2,5
top,CUST100001,2024-05-28,Male,Salaried,Nagpur,Personal Loan,1013000,Approved,Active
freq,1,133,61877,50619,8110,30075,4,62735,38946

## Find Unique Values

In [70]:

print(df["Gender"].unique().tolist())
print("======================================================")
print(df["Employment_Type"].unique().tolist())
print("======================================================")
print(df["Loan_Type"].unique().tolist())
print("======================================================")       
print(df["City"].unique().tolist())
print("======================================================") 
print(df["Approval_Status"].unique().tolist())
print("======================================================")
print(df["Loan_Status"].unique().tolist())
print("======================================================")
# we need To change Employment_Type unique values fromat

['Male', 'Female']
======================================================
['Salaried', 'Business', 'Freelancer', 'Self-Employed', 'business', ' Salaried ', ' Business ', ' Self-Employed ', 'self-employed', 'salaried', 'freelancer', ' Freelancer ']
======================================================
['Personal Loan', 'Home Loan', 'Auto Loan', 'Business Loan', 'Education Loan']
======================================================
['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Navi Mumbai', 'Aurangabad', 'Kolhapur', 'Solapur', 'Jalgaon', 'Ahmednagar', 'Amravati', 'ahmednagar', 'thane', ' Nashik ', 'pune', 'mumbai', 'solapur', 'aurangabad', ' Kolhapur ', ' Thane ', ' Jalgaon ', ' Mumbai ', ' Solapur ', ' Amravati ', 'nashik', ' Aurangabad ', 'navi mumbai', 'nagpur', ' Ahmednagar ', 'kolhapur', 'jalgaon', ' Nagpur ', ' Pune ', ' Navi Mumbai ', 'amravati']
======================================================
['Approved', 'Rejected']
======================================================
['Active', 'Overdue', 'Rejected', 'Closed', 'Default']
======================================================

# cheking Messing Values

In [71]:
df.isnull().sum()

Customer_ID           0
Application_Date      0
Age                   0
Gender                0
Employment_Type       0
Annual_Income         0
City                  0
Credit_Score          0
Loan_Type             0
Loan_Tenure_Years     0
Loan_Amount           0
Approval_Status       0
Loan_Status           0
Payment_Delay_Days    0
dtype: int64

# cheking duplicated Rows

In [72]:
df.duplicated().sum()

np.int64(0)

# wrong data Type

In [73]:
df.dtypes
## we need to change Application_Date  and Loan_Amount Data Type

Customer_ID            object
Application_Date       object
Age                     int64
Gender                 object
Employment_Type        object
Annual_Income         float64
City                   object
Credit_Score            int64
Loan_Type              object
Loan_Tenure_Years       int64
Loan_Amount            object
Approval_Status        object
Loan_Status            object
Payment_Delay_Days      int64
dtype: object

## Otlier Detection

In [74]:
print("Number Of outlier In age ",((df["Age"] < 0) | (df["Age"] > 100)).sum())
print("Number Of outlier In Annual_Income ",((df["Annual_Income"] < 0).sum()))
print ("Number Of outlier In Credit_Score ",((df["Credit_Score"] < 0) | (df["Age"] > 900)).sum())  	
print("Number Of outlier In Loan_Tenure_Years ",((df["Loan_Tenure_Years"] < 0).sum()))
print("Number Of outlier In Payment_Delay_Days ",((df["Payment_Delay_Days"] < 0).sum()))

Number Of outlier In age  0
Number Of outlier In Annual_Income  0
Number Of outlier In Credit_Score  0
Number Of outlier In Loan_Tenure_Years  0
Number Of outlier In Payment_Delay_Days  0